<script setup lang="ts">
import { Head, useForm } from '@inertiajs/vue3';
import { computed, watch } from 'vue';

interface Family { label: string; responsible_name: string | null; current_allocation: number; rsvp_status: string; attending_count: number | null; notifications: { id: number; title: string; description: string | null; created_at: string }[]; wedding: { id: number; name: string; timezone: string; events: { name: string; event_date: string | null; event_time: string | null; venue: string | null; starts_at: string | null }[] } }
const props = defineProps<{ family: Family; serverNow: string }>();
// Some mobile WebViews do not expose crypto.randomUUID(). A deterministic
// fallback keeps the public invitation from failing before it can render.
const newIdempotencyKey = () => globalThis.crypto?.randomUUID?.() ?? `rsvp-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const rsvpForm = useForm({ response: 'confirmed', attending_count: props.family.current_allocation, idempotency_key: newIdempotencyKey(), members: Array.from({ length: props.family.current_allocation }, () => ({ display_name: '', attending: true, dietary_restrictions: '', accessibility_needs: '' })) });
const seatsForm = useForm({ requested_count: 1, request_note: '' });
const event = computed(() => props.family.wedding.events[0]);
const formatDate = (value: string | null) => {
    const date = value?.slice(0, 10);
    return date ? new Intl.DateTimeFormat('es-MX', { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(`${date}T12:00:00Z`)) : 'Fecha pendiente';
};
watch(() => rsvpForm.attending_count, (count) => { while (rsvpForm.members.length < count) rsvpForm.members.push({ display_name: '', attending: true, dietary_restrictions: '', accessibility_needs: '' }); rsvpForm.members.forEach((member, index) => { member.attending = index < count; }); });
function submitRsvp(): void { rsvpForm.post(route('invitation.rsvp', route().params.token), { preserveScroll: true, onSuccess: () => { rsvpForm.idempotency_key = newIdempotencyKey(); } }); }
function requestExtraSeats(): void { seatsForm.post(route('invitation.additional-seats.store', route().params.token), { preserveScroll: true, onSuccess: () => seatsForm.reset() }); }
</script>

<template>
    <Head :title="`Invitación · ${family.wedding.name}`" />
    <main class="min-h-screen bg-[#fbf8f4] px-4 py-10 text-stone-800"><div class="mx-auto max-w-xl rounded-3xl border border-rose-100 bg-white p-7 shadow-sm sm:p-10">
        <p class="text-center text-sm uppercase tracking-[.25em] text-rose-700">Nos encantaría contar contigo</p><h1 class="mt-4 text-center font-serif text-4xl">{{ family.wedding.name }}</h1>
        <div class="mt-8 rounded-2xl bg-stone-800 p-5 text-stone-50"><p class="font-medium">{{ event?.name || 'Evento principal' }}</p><p class="mt-1 text-sm text-stone-200">{{ formatDate(event?.event_date ?? null) }}<span v-if="event?.event_time"> · {{ event.event_time?.slice(0, 5) }}</span><span v-if="event?.venue"> · {{ event.venue }}</span></p><a :href="route('gifts.index', family.wedding.id)" class="mt-3 inline-block text-sm text-rose-200 underline underline-offset-4">Ver lista de regalos</a></div>
        <section v-if="family.rsvp_status === 'confirmed'" class="mt-6 text-center"><h2 class="font-serif text-xl">Pase familiar</h2><p class="mt-1 text-sm text-stone-600">Presenta este código en recepción. No registra ingresos por sí solo.</p><img :src="route('invitation.qr', route().params.token)" alt="Código QR del pase familiar" class="mx-auto mt-3 h-40 w-40 rounded-lg border border-stone-200 p-2"></section>
        <section class="mt-8"><h2 class="font-serif text-2xl">Confirmación familiar</h2><p class="mt-2 text-sm text-stone-600">Familia {{ family.label }} · {{ family.current_allocation }} pases vigentes. El responsable cuenta solo si lo incluyes en la cantidad.</p><div v-if="family.rsvp_status !== 'pending'" class="mt-5 rounded-xl bg-rose-50 p-4 text-rose-900">Tu respuesta ya fue registrada: {{ family.rsvp_status }}<span v-if="family.attending_count !== null"> · {{ family.attending_count }} asistentes</span>. Para cambiarla, contacta a la empresa.</div><form v-else class="mt-5 space-y-4" @submit.prevent="submitRsvp"><fieldset class="flex gap-4"><label><input v-model="rsvpForm.response" type="radio" value="confirmed"> Asistiremos</label><label><input v-model="rsvpForm.response" type="radio" value="declined"> No asistiremos</label></fieldset><label v-if="rsvpForm.response === 'confirmed'" class="block text-sm">¿Cuántas personas asistirán?<input v-model.number="rsvpForm.attending_count" type="number" min="1" :max="family.current_allocation" class="mt-1 block w-full rounded-lg border-stone-300"><span class="mt-1 block text-stone-500">Si confirmas menos, los pases restantes se liberan inmediatamente.</span></label><div v-if="rsvpForm.response === 'confirmed'" class="space-y-3"><p class="text-sm font-medium">Datos opcionales de asistentes</p><div v-for="(_, index) in rsvpForm.attending_count" :key="index" class="rounded-xl border border-stone-200 p-3"><input v-model="rsvpForm.members[index].display_name" class="w-full rounded-lg border-stone-300" :placeholder="`Integrante ${index + 1}`"><input v-model="rsvpForm.members[index].dietary_restrictions" class="mt-2 w-full rounded-lg border-stone-300" placeholder="Alergias o restricciones (opcional)"><input v-model="rsvpForm.members[index].accessibility_needs" class="mt-2 w-full rounded-lg border-stone-300" placeholder="Necesidades de comodidad o accesibilidad (opcional)"></div></div><p v-if="rsvpForm.errors.attending_count || rsvpForm.errors.response" class="text-sm text-red-700">{{ rsvpForm.errors.attending_count || rsvpForm.errors.response }}</p><button class="rounded-lg bg-rose-800 px-4 py-2 text-sm font-medium text-white" :disabled="rsvpForm.processing">Enviar respuesta</button></form></section>
        <section v-if="family.rsvp_status !== 'declined'" class="mt-8 border-t border-stone-100 pt-6"><h2 class="font-serif text-xl">Solicitar lugares adicionales</h2><p class="mt-2 text-sm text-stone-600">Esta solicitud no reserva ni modifica tus pases; la empresa la revisará según el cupo disponible.</p><form class="mt-4 space-y-3" @submit.prevent="requestExtraSeats"><label class="block text-sm">Lugares solicitados<input v-model.number="seatsForm.requested_count" type="number" min="1" max="50" class="mt-1 block w-full rounded-lg border-stone-300"></label><textarea v-model="seatsForm.request_note" class="block w-full rounded-lg border-stone-300" rows="2" maxlength="1000" placeholder="Nota para la empresa (opcional)" /><p v-if="seatsForm.errors.requested_count || seatsForm.errors.request_note" class="text-sm text-red-700">{{ seatsForm.errors.requested_count || seatsForm.errors.request_note }}</p><button class="rounded-lg border border-rose-700 px-4 py-2 text-sm font-medium text-rose-800" :disabled="seatsForm.processing">Enviar solicitud</button></form></section>
        <section v-if="family.notifications.length" class="mt-8 border-t border-stone-100 pt-6"><h2 class="font-serif text-xl">Avisos</h2><article v-for="notice in family.notifications" :key="notice.id" class="mt-3 rounded-xl bg-stone-50 p-4"><p class="font-medium">{{ notice.title }}</p><p v-if="notice.description" class="mt-1 text-sm text-stone-600">{{ notice.description }}</p></article></section>
    </div></main>
</template>
