<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';

interface Wedding { id: number; name: string; support_type: string; authorized_capacity: number | null; timezone: string }
interface Interview { current_step: number; answers: Record<string, unknown> | null; last_saved_at: string | null }
const props = defineProps<{ wedding: Wedding; interview: Interview }>();
const answers = props.interview.answers ?? {};
const form = useForm({ current_step: props.interview.current_step, contact_name: String(answers.contact_name ?? ''), contact_email: String(answers.contact_email ?? ''), contact_phone: String(answers.contact_phone ?? ''), support_type: props.wedding.support_type, authorized_capacity: props.wedding.authorized_capacity as number | null, estimated_budget: answers.estimated_budget ? Number(answers.estimated_budget) : null as number | null, timezone: props.wedding.timezone, notes: String(answers.notes ?? ''), permissions: (answers.permissions ?? {}) as Record<string, boolean> });
function goTo(step: number): void { form.current_step = step; }
function save(next?: number): void { if (next) form.current_step = next; form.put(route('weddings.interview.update', props.wedding.id), { preserveScroll: true }); }
</script>

<template>
    <Head :title="`Entrevista · ${wedding.name}`" />
    <AuthenticatedLayout>
        <template #header><div><Link :href="route('weddings.workspace', wedding.id)" class="text-sm text-rose-800 underline">← Centro</Link><h1 class="mt-1 font-serif text-3xl text-stone-800">Entrevista inicial</h1></div></template>
        <div class="mx-auto max-w-3xl px-4 py-8 sm:px-6"><form @submit.prevent="save()" class="space-y-6 rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><div><p class="text-sm text-stone-600">Guarda como borrador en cualquier momento. Paso {{ form.current_step }} de 4.</p><div class="mt-4 grid grid-cols-4 gap-2"><button v-for="step in 4" :key="step" type="button" class="rounded-lg px-3 py-2 text-sm" :class="step === form.current_step ? 'bg-rose-800 text-white' : 'bg-stone-100 text-stone-700'" @click="goTo(step)">Paso {{ step }}</button></div></div>
                <section v-if="form.current_step === 1" class="space-y-4"><h2 class="font-serif text-2xl">Contacto principal</h2><label class="block text-sm text-stone-700">Nombre<input v-model="form.contact_name" class="mt-1 w-full rounded-lg border-stone-300"></label><label class="block text-sm text-stone-700">Correo<input v-model="form.contact_email" type="email" class="mt-1 w-full rounded-lg border-stone-300"></label><label class="block text-sm text-stone-700">Teléfono / WhatsApp<input v-model="form.contact_phone" class="mt-1 w-full rounded-lg border-stone-300"></label></section>
                <section v-if="form.current_step === 2" class="grid gap-4 sm:grid-cols-2"><h2 class="font-serif text-2xl sm:col-span-2">Configuración y capacidad</h2><label class="text-sm text-stone-700">Acompañamiento<select v-model="form.support_type" class="mt-1 w-full rounded-lg border-stone-300"><option value="full">Organización integral</option><option value="shared">Organización compartida</option><option value="advisory">Asesoría</option></select></label><label class="text-sm text-stone-700">Cupo autorizado<input v-model.number="form.authorized_capacity" type="number" min="1" class="mt-1 w-full rounded-lg border-stone-300"></label><label class="text-sm text-stone-700 sm:col-span-2">Zona horaria<select v-model="form.timezone" class="mt-1 w-full rounded-lg border-stone-300"><option value="America/Mexico_City">México central</option><option value="America/Tijuana">México noroeste</option><option value="America/Cancun">Quintana Roo</option></select></label></section>
                <section v-if="form.current_step === 3" class="space-y-4"><h2 class="font-serif text-2xl">Presupuesto y notas</h2><label class="block text-sm text-stone-700">Presupuesto estimado<input v-model.number="form.estimated_budget" type="number" min="0" step="0.01" class="mt-1 w-full rounded-lg border-stone-300"></label><label class="block text-sm text-stone-700">Notas de entrevista<textarea v-model="form.notes" rows="6" class="mt-1 w-full rounded-lg border-stone-300" /></label></section>
                <section v-if="form.current_step === 4" class="space-y-3"><h2 class="font-serif text-2xl">Revisión antes de activar</h2><dl class="grid gap-3 rounded-xl bg-stone-50 p-4 text-sm sm:grid-cols-2"><div><dt class="text-stone-500">Contacto</dt><dd class="font-medium">{{ form.contact_name || 'Pendiente' }}</dd></div><div><dt class="text-stone-500">Acompañamiento</dt><dd class="font-medium">{{ form.support_type === 'full' ? 'Organización integral' : form.support_type === 'shared' ? 'Organización compartida' : 'Asesoría' }}</dd></div><div><dt class="text-stone-500">Cupo</dt><dd class="font-medium">{{ form.authorized_capacity ?? 'Pendiente' }}</dd></div><div><dt class="text-stone-500">Presupuesto</dt><dd class="font-medium">{{ form.estimated_budget ?? 'Pendiente' }}</dd></div></dl><p class="rounded-lg bg-rose-50 p-3 text-sm text-stone-700"><b>Qué sucede después:</b> guarda esta revisión, abre el expediente y confirma con el botón “Activar configuración revisada”. Esa acción deja trazabilidad y notifica a la pareja; no se activa automáticamente al guardar.</p></section>
                <p v-if="form.hasErrors" class="text-sm text-red-700">Revisa los campos marcados antes de guardar.</p><div class="flex flex-wrap gap-3"><button type="submit" class="rounded-lg bg-rose-800 px-4 py-2 text-sm font-medium text-white disabled:opacity-50" :disabled="form.processing">Guardar borrador</button><button v-if="form.current_step < 4" type="button" class="rounded-lg border border-stone-300 px-4 py-2 text-sm" @click="save(form.current_step + 1)">Guardar y continuar</button><Link v-if="form.current_step === 4" :href="route('weddings.show', wedding.id)" class="rounded-lg border border-rose-700 px-4 py-2 text-sm text-rose-800">Abrir expediente para activar</Link></div></form></div>
    </AuthenticatedLayout>
</template>
