<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { ref } from 'vue';

interface Proposal { id: number; title: string; description: string | null; amount: string | null; status: string; couple_comment: string | null; version: number }
interface Task { id: number; title: string; priority: string; due_date: string | null; status: string }
interface Wedding { id: number; name: string; tasks: Task[]; agenda_items: { id: number; title: string; starts_at: string | null; ends_at: string | null; location: string | null; category: string; notes: string | null }[]; proposals: Proposal[]; participants: { id: number; name: string; role: string; phone: string | null; schedule_note: string | null }[]; menu_options: { id: number; name: string; description: string | null }[]; tables: { id: number; label: string; capacity: number; members: { id: number }[] }[] }
const props = defineProps<{ wedding: Wedding; canEdit: boolean; canApprove: boolean }>();
const taskForm = useForm({ title: '', priority: 'normal', due_date: '' });
const agendaForm = useForm({ title: '', starts_at: '', ends_at: '', location: '', category: 'other', notes: '' });
const proposalForm = useForm({ title: '', description: '', amount: null as number | null });
const participantForm = useForm({ name: '', role: '', phone: '', schedule_note: '' });
const menuForm = useForm({ name: '', description: '' });
const tableForm = useForm({ label: '', capacity: 8 });
const revising = ref<number | null>(null);
const formatDateTime = (value: string | null) => value ? new Intl.DateTimeFormat('es-MX', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/Mexico_City' }).format(new Date(value)) : 'Pendiente';
function post(form: ReturnType<typeof useForm>, name: string): void { form.post(route(name, props.wedding.id), { preserveScroll: true, onSuccess: () => form.reset() }); }
function updateTask(item: Task, event: Event): void { router.patch(route('weddings.planning.tasks.update', [props.wedding.id, item.id]), { status: (event.target as HTMLSelectElement).value }, { preserveScroll: true }); }
function decide(item: Proposal, decision: string): void { router.patch(route('weddings.planning.proposals.decide', [props.wedding.id, item.id]), { decision }, { preserveScroll: true }); }
function startRevision(item: Proposal): void { revising.value = item.id; proposalForm.title = item.title; proposalForm.description = item.description ?? ''; proposalForm.amount = item.amount === null ? null : Number(item.amount); }
function submitProposal(): void { const routeName = revising.value ? route('weddings.planning.proposals.revise', [props.wedding.id, revising.value]) : route('weddings.planning.proposals.store', props.wedding.id); proposalForm.post(routeName, { preserveScroll: true, onSuccess: () => { proposalForm.reset(); revising.value = null; } }); }
</script>

<template>
    <Head :title="`Planeación · ${wedding.name}`" />
    <AuthenticatedLayout>
        <template #header><div><Link :href="route('weddings.workspace', wedding.id)" class="text-sm text-rose-800 underline">← Centro</Link><h1 class="mt-1 font-serif text-3xl">Planeación</h1></div></template>
        <div class="mx-auto grid max-w-6xl gap-6 px-4 py-8 lg:grid-cols-3">
<section class="rounded-2xl border bg-white p-5"><h2 class="font-serif text-xl">Tareas</h2><div v-for="item in wedding.tasks" :key="item.id" class="mt-3 border-t pt-3 text-sm"><b>{{ item.title }}</b><p class="text-stone-600">{{ item.priority }} · {{ formatDateTime(item.due_date) }}</p><label v-if="canEdit" class="mt-2 block text-xs">Estado<select :value="item.status" class="mt-1 rounded border-stone-300 text-sm" @change="updateTask(item, $event)"><option value="pending">Pendiente</option><option value="in_progress">En proceso</option><option value="completed">Completada</option></select></label><p v-else class="mt-1 text-stone-500">{{ item.status }}</p></div><form v-if="canEdit" class="mt-4 space-y-2" @submit.prevent="post(taskForm, 'weddings.planning.tasks.store')"><label class="block text-sm">Nombre de la tarea<input v-model="taskForm.title" required class="mt-1 w-full rounded border-stone-300" placeholder="Ej. Confirmar flores"/></label><label class="block text-sm">Prioridad<select v-model="taskForm.priority" class="mt-1 w-full rounded border-stone-300"><option value="low">Baja</option><option value="normal">Normal</option><option value="high">Alta</option></select></label><label class="block text-sm">Fecha límite<input v-model="taskForm.due_date" type="date" class="mt-1 w-full rounded border-stone-300"/></label><button class="rounded bg-rose-800 px-3 py-2 text-sm text-white">Agregar tarea</button></form></section>
            <section class="rounded-2xl border bg-white p-5"><h2 class="font-serif text-xl">Agenda del día</h2><div v-for="item in wedding.agenda_items" :key="item.id" class="mt-3 border-t pt-3 text-sm"><b>{{ item.title }}</b><p class="text-stone-600">{{ item.category }} · {{ formatDateTime(item.starts_at) }}<span v-if="item.ends_at"> — {{ formatDateTime(item.ends_at) }}</span></p><p v-if="item.location || item.notes" class="text-stone-500">{{ item.location }}{{ item.notes ? ` · ${item.notes}` : '' }}</p></div><form v-if="canEdit" class="mt-4 space-y-2" @submit.prevent="post(agendaForm, 'weddings.planning.agenda.store')"><input v-model="agendaForm.title" required class="w-full rounded border-stone-300" placeholder="Momento de agenda"><div class="grid grid-cols-2 gap-2"><input v-model="agendaForm.starts_at" type="datetime-local" class="w-full rounded border-stone-300"><input v-model="agendaForm.ends_at" type="datetime-local" class="w-full rounded border-stone-300"></div><select v-model="agendaForm.category" class="w-full rounded border-stone-300"><option value="setup">Montaje</option><option value="ceremony">Ceremonia</option><option value="photos">Fotografías</option><option value="transport">Traslado</option><option value="meal">Comida</option><option value="cake">Pastel</option><option value="closing">Cierre</option><option value="other">Otro</option></select><input v-model="agendaForm.location" class="w-full rounded border-stone-300" placeholder="Lugar"><textarea v-model="agendaForm.notes" class="w-full rounded border-stone-300" placeholder="Notas operativas"/><button class="rounded bg-rose-800 px-3 py-2 text-sm text-white">Agregar momento</button></form></section>
            <section class="rounded-2xl border bg-white p-5"><h2 class="font-serif text-xl">Propuestas</h2><article v-for="item in wedding.proposals" :key="item.id" class="mt-3 border-t pt-3 text-sm"><b>{{ item.title }}</b><p>{{ item.status }} · versión {{ item.version }}<span v-if="item.amount !== null"> · ${{ item.amount }}</span></p><p v-if="item.description">{{ item.description }}</p><p v-if="item.couple_comment" class="text-stone-600">{{ item.couple_comment }}</p><div v-if="canApprove && item.status === 'sent'" class="mt-2 flex gap-2"><button class="rounded bg-rose-800 px-2 py-1 text-white" @click="decide(item, 'approved')">Aprobar</button><button class="rounded border px-2 py-1" @click="decide(item, 'changes_requested')">Pedir cambios</button></div><button v-if="canEdit" class="mt-2 rounded border border-stone-400 px-2 py-1" @click="startRevision(item)">Crear nueva versión</button></article><form v-if="canEdit" class="mt-4 space-y-2" @submit.prevent="submitProposal"><h3 class="font-medium">{{ revising ? 'Nueva versión de propuesta' : 'Nueva propuesta' }}</h3><input v-model="proposalForm.title" required class="w-full rounded border-stone-300" placeholder="Propuesta"><textarea v-model="proposalForm.description" class="w-full rounded border-stone-300" placeholder="Descripción"/><input v-model.number="proposalForm.amount" type="number" min="0" step="0.01" class="w-full rounded border-stone-300" placeholder="Importe"><div class="flex gap-2"><button class="rounded bg-rose-800 px-3 py-2 text-sm text-white">{{ revising ? 'Enviar versión' : 'Enviar propuesta' }}</button><button v-if="revising" type="button" class="rounded border px-3 py-2 text-sm" @click="revising = null; proposalForm.reset()">Cancelar</button></div></form></section>
            <section class="rounded-2xl border bg-white p-5"><h2 class="font-serif text-xl">Participantes</h2><div v-for="item in wedding.participants" :key="item.id" class="mt-2 text-sm"><b>{{ item.name }}</b> · {{ item.role }}<span v-if="item.phone"> · {{ item.phone }}</span><span v-if="item.schedule_note"> · {{ item.schedule_note }}</span></div><form v-if="canEdit" class="mt-4 space-y-2" @submit.prevent="post(participantForm, 'weddings.planning.participants.store')"><input v-model="participantForm.name" required class="w-full rounded border-stone-300" placeholder="Nombre"><input v-model="participantForm.role" required class="w-full rounded border-stone-300" placeholder="Función"><input v-model="participantForm.phone" class="w-full rounded border-stone-300" placeholder="Teléfono"><input v-model="participantForm.schedule_note" class="w-full rounded border-stone-300" placeholder="Horario o nota"><button class="rounded bg-rose-800 px-3 py-2 text-sm text-white">Agregar participante</button></form></section>
            <section class="rounded-2xl border bg-white p-5"><h2 class="font-serif text-xl">Menú</h2><p v-for="item in wedding.menu_options" :key="item.id" class="mt-2 text-sm"><b>{{ item.name }}</b> {{ item.description }}</p><form v-if="canEdit" class="mt-4 space-y-2" @submit.prevent="post(menuForm, 'weddings.planning.menu.store')"><input v-model="menuForm.name" required class="w-full rounded border-stone-300" placeholder="Opción"><textarea v-model="menuForm.description" class="w-full rounded border-stone-300" placeholder="Descripción"/><button class="rounded bg-rose-800 px-3 py-2 text-sm text-white">Agregar opción</button></form></section>
            <section class="rounded-2xl border bg-white p-5"><h2 class="font-serif text-xl">Mesas</h2><p v-for="item in wedding.tables" :key="item.id" class="mt-2 text-sm"><b>{{ item.label }}</b> · {{ item.members.length }}/{{ item.capacity }} lugares</p><form v-if="canEdit" class="mt-4 space-y-2" @submit.prevent="post(tableForm, 'weddings.planning.tables.store')"><input v-model="tableForm.label" required class="w-full rounded border-stone-300" placeholder="Mesa"><input v-model.number="tableForm.capacity" type="number" min="1" class="w-full rounded border-stone-300"><button class="rounded bg-rose-800 px-3 py-2 text-sm text-white">Agregar mesa</button></form></section>
        </div>
    </AuthenticatedLayout>
</template>
