<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, router } from '@inertiajs/vue3';
interface Member { id: number; display_name: string | null; attending: boolean; dietary_restrictions: string | null; wedding_table_id: number | null; family: { label: string } }
interface Table { id: number; label: string; capacity: number; members: Member[] }
const props = defineProps<{ wedding: { id: number; name: string; tables: Table[]; guest_families: { label: string; members: Member[] }[] }; canEdit: boolean }>();
function assign(member: Member, tableId: number | null): void { router.patch(route('weddings.planning.members.assign-table', [props.wedding.id, member.id]), { wedding_table_id: tableId }, { preserveScroll: true }); }
const unseated = () => props.wedding.guest_families.flatMap((family) => family.members).filter((member) => member.attending && !member.wedding_table_id);
const dietary = () => props.wedding.guest_families.flatMap((family) => family.members).filter((member) => member.attending && member.dietary_restrictions);
</script>
<template><Head :title="`Mesas · ${wedding.name}`"/><AuthenticatedLayout><template #header><div><Link :href="route('weddings.planning.index', wedding.id)" class="text-sm text-rose-800 underline">← Planeación</Link><h1 class="mt-1 font-serif text-3xl">Mesas y cocina</h1></div></template><div class="mx-auto max-w-6xl px-4 py-8"><section class="grid gap-4 md:grid-cols-3"><article v-for="table in wedding.tables" :key="table.id" class="rounded-2xl border bg-white p-5"><h2 class="font-serif text-xl">{{ table.label }}</h2><p class="text-sm text-stone-600">{{ table.members.length }}/{{ table.capacity }} lugares</p><p v-for="member in table.members" :key="member.id" class="mt-2 text-sm">{{ member.display_name || 'Integrante sin nombre' }} · {{ member.family.label }}</p></article></section><section class="mt-6 rounded-2xl border bg-white p-5"><h2 class="font-serif text-xl">Confirmados sin mesa</h2><p v-if="!unseated().length" class="mt-2 text-sm text-stone-500">Todos los integrantes confirmados están asignados.</p><div v-for="member in unseated()" :key="member.id" class="mt-3 flex flex-wrap items-center gap-3 border-t pt-3 text-sm"><span>{{ member.display_name || 'Integrante sin nombre' }} · {{ member.family.label }}</span><select v-if="canEdit" class="rounded border-stone-300" @change="assign(member, Number(($event.target as HTMLSelectElement).value))"><option value="">Asignar mesa</option><option v-for="table in wedding.tables" :key="table.id" :value="table.id">{{ table.label }}</option></select></div></section><section class="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 class="font-serif text-xl">Reporte para cocina</h2><p v-if="!dietary().length" class="mt-2 text-sm text-amber-900">No hay restricciones registradas.</p><p v-for="member in dietary()" :key="member.id" class="mt-2 text-sm text-amber-950"><b>{{ member.display_name || 'Integrante sin nombre' }}</b> · {{ member.family.label }} · {{ member.dietary_restrictions }}</p></section></div></AuthenticatedLayout></template>
