<?php
namespace App\Http\Controllers;
use App\Models\GiftReservation; use App\Models\Wedding; use App\Models\WeddingGift; use App\Models\WeddingAudit; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException; use Inertia\Inertia;
class GiftController extends Controller { use \Illuminate\Foundation\Auth\Access\AuthorizesRequests;
public function index(Wedding $wedding) { return Inertia::render('Gifts/Index',['wedding'=>$wedding,'gifts'=>$wedding->gifts()->where('is_active',true)->get()]); }
public function manage(Request $request, Wedding $wedding) { $this->authorize('update',$wedding); return Inertia::render('Gifts/Manage',['wedding'=>$wedding,'gifts'=>$wedding->gifts()->with('reservations')->get()]); }
public function store(Request $request, Wedding $wedding) { $this->authorize('update',$wedding); $wedding->gifts()->create($request->validate(['name'=>['required','string','max:180'],'description'=>['nullable','string','max:2000'],'quantity'=>['required','integer','min:1'],'reference_url'=>['nullable','url','max:2000']])); return back()->with('success','Regalo agregado.'); }
public function reserve(Request $request, Wedding $wedding, WeddingGift $gift) { abort_unless($gift->wedding_id===$wedding->id,404); $data=$request->validate(['guest_name'=>['required','string','max:180'],'guest_email'=>['nullable','email','max:180'],'quantity'=>['required','integer','min:1'],'idempotency_key'=>['required','uuid']]); DB::transaction(function() use($gift,$data){ $item=WeddingGift::query()->lockForUpdate()->findOrFail($gift->id); if (GiftReservation::where('wedding_gift_id',$item->id)->where('idempotency_key',$data['idempotency_key'])->exists()) return; if (!$item->is_active || $item->quantity-$item->reserved_quantity<$data['quantity']) throw ValidationException::withMessages(['quantity'=>'No quedan unidades disponibles.']); $item->increment('reserved_quantity',$data['quantity']); $item->reservations()->create($data); }); return back()->with('success','Regalo reservado.'); }
public function release(Request $request, Wedding $wedding, GiftReservation $reservation) { $this->authorize('update',$wedding); $data=$request->validate(['reason'=>['required','string','max:1000']]); DB::transaction(function() use($reservation,$wedding,$data,$request){ $row=GiftReservation::query()->lockForUpdate()->findOrFail($reservation->id); $gift=WeddingGift::query()->lockForUpdate()->findOrFail($row->wedding_gift_id); abort_unless($gift->wedding_id===$wedding->id && $row->released_at===null,404); $gift->decrement('reserved_quantity',$row->quantity); $row->update(['released_at'=>now()]); WeddingAudit::create(['wedding_id'=>$wedding->id,'actor_id'=>$request->user()->id,'action'=>'gift.reservation_released','subject_type'=>GiftReservation::class,'subject_id'=>$row->id,'after'=>['quantity'=>$row->quantity,'reason'=>$data['reason']]]); }); return back()->with('success','Reserva liberada y auditada.'); }
}
