<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, router, useForm } from '@inertiajs/vue3';
interface Entry { id: number; count: number; entered_at: string; operator: { name: string } | null }
interface Family { id: number; label: string; rsvp_status: string; attending_count: number | null; entered_count: number | null; access_entries?: Entry[] }
const props = defineProps<{ wedding: { id: number; name: string }; families: Family[]; selected: Family | null }>();
const newIdempotencyKey = (): string => globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(16).slice(2)}-${Math.random().toString(16).slice(2)}`;
const form = useForm({ count: 1, idempotency_key: newIdempotencyKey() });
const lookupForm = useForm({ code: '' });
const correctionForm = useForm({ reason: '' });
function remaining(family: Family): number { return Math.max(0, (family.rsvp_status === 'confirmed' ? family.attending_count ?? 0 : 0) - (family.entered_count ?? 0)); }
function record(family: Family): void { form.post(route('weddings.reception.record', [props.wedding.id, family.id]), { preserveScroll: true, preserveState: true, onSuccess: () => { form.idempotency_key = newIdempotencyKey(); } }); }
function lookup(): void { router.get(route('weddings.reception.index', props.wedding.id), { code: lookupForm.code }, { preserveState: true }); }
function correct(entry: Entry): void { correctionForm.delete(route('weddings.reception.correct', [props.wedding.id, entry.id]), { preserveScroll: true, onSuccess: () => correctionForm.reset() }); }
</script>
<template><Head :title="`Recepción · ${wedding.name}`"/><AuthenticatedLayout><template #header><h1 class="font-serif text-3xl text-stone-800">Recepción · {{ wedding.name }}</h1></template><div class="mx-auto max-w-5xl px-4 py-8"><p class="text-sm text-stone-600">Pega el enlace leído del QR o busca en la lista. Consultar el código no consume ningún acceso.</p><form class="mt-4 flex gap-2" @submit.prevent="lookup"><input v-model="lookupForm.code" class="min-w-0 flex-1 rounded-lg border-stone-300" placeholder="Enlace o código de invitación"><button class="rounded-lg border border-stone-700 px-3 py-2 text-sm text-stone-800">Consultar pase</button></form><section v-if="selected" class="mt-6 rounded-xl border border-rose-200 bg-rose-50 p-4"><p class="font-medium">Consulta: {{ selected.label }}</p><p class="mt-1 text-sm">Confirmados: {{ selected.rsvp_status === 'confirmed' ? selected.attending_count : 0 }} · Ingresaron: {{ selected.entered_count ?? selected.access_entries?.reduce((sum, entry) => sum + entry.count, 0) ?? 0 }}</p><div v-if="selected.access_entries?.length" class="mt-3 text-sm"><p class="font-medium">Historial de ingresos</p><div v-for="entry in selected.access_entries" :key="entry.id" class="mt-2 flex flex-wrap items-center gap-2"><span>{{ entry.count }} persona(s) · {{ entry.operator?.name || 'Operador eliminado' }}</span><form v-if="$page.props.auth.user.role === 'admin'" class="flex gap-2" @submit.prevent="correct(entry)"><input v-model="correctionForm.reason" required class="rounded border-stone-300 text-xs" placeholder="Motivo de corrección"><button class="rounded border border-stone-400 px-2 text-xs">Corregir</button></form></div></div></section><div class="mt-6 space-y-3"><article v-for="family in families" :key="family.id" class="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-stone-200 bg-white p-4"><div><p class="font-medium text-stone-800">{{ family.label }}</p><p class="text-sm text-stone-600">Confirmados: {{ family.rsvp_status === 'confirmed' ? family.attending_count : 0 }} · Ingresaron: {{ family.entered_count ?? 0 }} · Restan: {{ remaining(family) }}</p></div><form v-if="remaining(family)" class="flex items-center gap-2" @submit.prevent="record(family)"><input v-model.number="form.count" type="number" min="1" :max="remaining(family)" class="w-20 rounded-lg border-stone-300"><button class="rounded-lg bg-stone-800 px-3 py-2 text-sm text-white">Registrar ingreso</button></form><span v-else class="text-sm font-medium text-stone-500">{{ family.rsvp_status === 'confirmed' ? 'Pase completado' : 'Sin confirmación' }}</span></article></div><p v-if="form.errors.count" class="mt-4 text-sm text-red-700">{{ form.errors.count }}</p></div></AuthenticatedLayout></template>
